DROP TABLE IF EXISTS Event_participation;
DROP TABLE IF EXISTS Volunteering_participation;
DROP TABLE IF EXISTS Event;
DROP TABLE IF EXISTS Volunteering;
DROP TABLE IF EXISTS KindOfVol;
DROP TABLE IF EXISTS Patient;
DROP TABLE IF EXISTS City;
DROP TABLE IF EXISTS Volunteer;